# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_kilitle(object):
    def setupUi(self, kilitle):
        kilitle.setObjectName("kilitle")
        kilitle.resize(213, 168)
        self.label = QtWidgets.QLabel(kilitle)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(kilitle)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label_2.setObjectName("label_2")
        self.passbton = QtWidgets.QPushButton(kilitle)
        self.passbton.setGeometry(QtCore.QRect(10, 110, 71, 31))
        self.passbton.setObjectName("passbton")
        self.dosya = QtWidgets.QLineEdit(kilitle)
        self.dosya.setGeometry(QtCore.QRect(70, 20, 113, 20))
        self.dosya.setObjectName("dosya")
        self.sifre = QtWidgets.QLineEdit(kilitle)
        self.sifre.setGeometry(QtCore.QRect(70, 50, 113, 20))
        self.sifre.setObjectName("sifre")
        self.cozbton = QtWidgets.QPushButton(kilitle)
        self.cozbton.setGeometry(QtCore.QRect(110, 110, 71, 31))
        self.cozbton.setObjectName("cozbton")

        self.retranslateUi(kilitle)
        QtCore.QMetaObject.connectSlotsByName(kilitle)

    def retranslateUi(self, kilitle):
        _translate = QtCore.QCoreApplication.translate
        kilitle.setWindowTitle(_translate("kilitle", "Şifrele"))
        self.label.setText(_translate("kilitle", "Dosya yolu:"))
        self.label_2.setText(_translate("kilitle", "Şifre gir:"))
        self.passbton.setText(_translate("kilitle", "Şifrele"))
        self.cozbton.setText(_translate("kilitle", "ŞifreÇöz"))
